In [4]:
import pandas as pd

## events -> dataset

In [5]:
df = pd.read_csv("../data/raw/events.csv")

In [6]:
df.head()

,timestamp,visitorid,event,itemid,transactionid
0,1433221332117,257597,view,355908,NaN
1,1433224214164,992329,view,248676,NaN
2,1433221999827,111016,view,318965,NaN
3,1433221955914,483717,view,253185,NaN
4,1433221337106,951259,view,367447,NaN


In [7]:
df.shape


(2756101, 5)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2756101 entries, 0 to 2756100
Data columns (total 5 columns):
 #   Column         Dtype  
---  ------         -----  
 0   timestamp      int64  
 1   visitorid      int64  
 2   event          str    
 3   itemid         int64  
 4   transactionid  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 105.1 MB


In [9]:
df["visitorid"].nunique()


1407580

In [10]:
df["itemid"].nunique()

235061

In [11]:
df["event"].value_counts()

event
view           2664312
addtocart        69332
transaction      22457
Name: count, dtype: int64

In [12]:
df["visitorid"].nunique() * df["itemid"].nunique()

330867162380

## item_properties -> dataset

In [13]:
items = pd.read_csv("../data/raw/item_properties_part1.csv")

In [14]:
items.head()

,timestamp,itemid,property,value
0,1435460400000,460429,categoryid,1338
1,1441508400000,206783,888,1116713 960601 n277.200
2,1439089200000,395014,400,n552.000 639502 n720.000 424566
3,1431226800000,59481,790,n15360.000
4,1431831600000,156781,917,828513


In [15]:
items.shape

(10999999, 4)

In [16]:
items["property"].nunique()

1097

In [17]:
items["property"].value_counts().head(15)

property
888           1629817
790            970800
available      817387
categoryid     426305
6              343207
283            323681
776            311654
678            261829
364            256340
202            242984
839            226921
159            226502
917            226437
764            226242
112            226102
Name: count, dtype: int64

In [18]:
items["itemid"].nunique()

417053

In [19]:
items.shape


(10999999, 4)

## category_tree -> dataset

In [20]:
categories = pd.read_csv("../data/raw/category_tree.csv")

In [21]:
categories.head()

,categoryid,parentid
0,1016,213.0
1,809,169.0
2,570,9.0
3,1691,885.0
4,536,1691.0


## items2 -> dataset

In [22]:
items2 = pd.read_csv("../data/raw/item_properties_part2.csv")

In [23]:
items.head()

,timestamp,itemid,property,value
0,1435460400000,460429,categoryid,1338
1,1441508400000,206783,888,1116713 960601 n277.200
2,1439089200000,395014,400,n552.000 639502 n720.000 424566
3,1431226800000,59481,790,n15360.000
4,1431831600000,156781,917,828513


In [24]:
items2.shape

(9275903, 4)

In [25]:
df['visitorid'].value_counts().head(15)

visitorid
1150086    7757
530559     4328
152963     3024
895999     2474
163561     2410
371606     2345
286616     2252
684514     2246
892013     2024
861299     1991
836635     1934
76757      1883
638482     1829
1297062    1822
316850     1752
Name: count, dtype: int64

In [26]:
items["property"].value_counts().head(20)

property
888           1629817
790            970800
available      817387
categoryid     426305
6              343207
283            323681
776            311654
678            261829
364            256340
202            242984
839            226921
159            226502
917            226437
764            226242
112            226102
227            188209
698            157281
451            142388
663            131331
962            128976
Name: count, dtype: int64

In [27]:
items[items["property"] == "888"]["value"].nunique()

281842

In [28]:
items[items["property"] == "888"]["value"].head(20)

1                                1116713 960601 n277.200
10                                1038400 45956 n504.000
17                                               1292080
26             150169 176547 824301 24474 293011 1240134
40                                                599031
45                                         883447 726612
48     1051803 1227205 n712862568.000 992862 951748 6...
57                                        1024724 220869
65                  n120.000 586893 1166722 237874 43137
75                                        297660 1301543
77                                113942 492465 n168.000
93                                 543080 702002 n48.000
98                 824508 n7536.000 309080 594060 892470
104          1333963 747375 927741 1071593 547687 199524
109             150169 460346 174342 750333 523033 33148
113                               236689 1037087 1318567
126                                               665993
139    722389 543387 679871 n18

In [29]:
items[items["property"] == "888"]["value"].str.split().str.len().value_counts().head(10)

value
1     438546
2     422320
3     258343
4     142058
5      82974
6      50321
7      40096
8      27127
9      23232
10     19395
Name: count, dtype: int64

In [30]:
items[items["property"] == "categoryid"]["value"].nunique()

1196

In [31]:
category_data = items[items["property"] == "categoryid"]

In [32]:
category_data.groupby("itemid")["value"].nunique().value_counts().head(10)

value
1    215074
2     13174
3      1066
4        27
Name: count, dtype: int64

In [33]:

category_data["itemid"].nunique()


229341

In [34]:
all_items = pd.concat([items, items2], ignore_index=True)

In [35]:
all_items.shape

(20275902, 4)

In [36]:
interacted_items = df["itemid"].unique()

In [37]:
len(interacted_items)

235061

In [38]:
product_items = all_items[all_items["itemid"].isin(interacted_items)]

In [39]:
product_items.shape

(10180153, 4)

In [40]:
product_items[["itemid", "property", "value"]].duplicated().sum()

np.int64(4285682)

In [41]:
product_features = product_items[["itemid", "property", "value"]].drop_duplicates()

In [42]:
product_features.shape

(5894471, 3)

In [43]:
product_features.groupby("itemid")

In [44]:
product_features.head(10)

,itemid,property,value
0,460429,categoryid,1338
1,206783,888,1116713 960601 n277.200
2,395014,400,n552.000 639502 n720.000 424566
3,59481,790,n15360.000
4,156781,917,828513
5,285026,available,0
7,264312,6,319724
9,98113,451,1141052 n48.000
11,244127,400,n552.000 639502 n720.000 424566
14,169055,790,n21000.000


In [45]:
product_features["feature"] = (
    product_features["property"].astype(str)
    + "_"
    + product_features["value"].astype(str)
)

In [46]:
product_features.head(10)

,itemid,property,value,feature
0,460429,categoryid,1338,categoryid_1338
1,206783,888,1116713 960601 n277.200,888_1116713 960601 n277.200
2,395014,400,n552.000 639502 n720.000 424566,400_n552.000 639502 n720.000 424566
3,59481,790,n15360.000,790_n15360.000
4,156781,917,828513,917_828513
5,285026,available,0,available_0
7,264312,6,319724,6_319724
9,98113,451,1141052 n48.000,451_1141052 n48.000
11,244127,400,n552.000 639502 n720.000 424566,400_n552.000 639502 n720.000 424566
14,169055,790,n21000.000,790_n21000.000


In [47]:
product_features["feature"] = (
    product_features["property"].astype(str)
    + "_"
    + product_features["value"].astype(str)
)

In [48]:
product_features.head(10)

,itemid,property,value,feature
0,460429,categoryid,1338,categoryid_1338
1,206783,888,1116713 960601 n277.200,888_1116713 960601 n277.200
2,395014,400,n552.000 639502 n720.000 424566,400_n552.000 639502 n720.000 424566
3,59481,790,n15360.000,790_n15360.000
4,156781,917,828513,917_828513
5,285026,available,0,available_0
7,264312,6,319724,6_319724
9,98113,451,1141052 n48.000,451_1141052 n48.000
11,244127,400,n552.000 639502 n720.000 424566,400_n552.000 639502 n720.000 424566
14,169055,790,n21000.000,790_n21000.000


In [49]:
product_profiles = (
    product_features.groupby("itemid")["feature"]
    .apply(" ".join)
)

In [50]:
product_profiles.head()

itemid
3     159_519769 available_0 678_327918 1080_769062 ...
4     available_0 115_n24.000 897_324209 28_150169 1...
6     categoryid_1091 28_150169 610517 713_373898 91...
15    839_245772 790_n0.000 283_433564 245772 789221...
16    328_1042438 839_71304 28_150169 431733 1036_11...
Name: feature, dtype: str

In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(product_profiles)
tfidf_matrix.shape

(185246, 1005471)

In [52]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(tfidf_matrix[0],tfidf_matrix)
similarity.shape

(1, 185246)

In [53]:
similarity[0].argsort()

array([ 38799,  15684, 152988, ...,  47522,  58928,      0],
      shape=(185246,))

In [54]:
similarity[0].argsort()[::-1]

array([     0,  58928,  47522, ..., 152988,  15684,  38799],
      shape=(185246,))

In [55]:
similar_products = similarity[0].argsort()[::-1][:11]

similar_products

array([     0,  58928,  47522, 131804, 120470, 142596,   4291,  17448,
        71388, 157643,  88201])

In [56]:
product_profiles.index[0]

np.int64(3)

In [57]:
recommended_itemids = product_profiles.index[similar_products]

recommended_itemids

Index([3, 147758, 119022, 331919, 303129, 358775, 10928, 43849, 179634, 396926,
       222126],
      dtype='int64', name='itemid')

In [58]:
similarity_scores = similarity[0][similar_products]

similarity_scores

array([1.        , 0.52710716, 0.38032628, 0.36819381, 0.35643634,
       0.35629803, 0.35395451, 0.33020826, 0.32381026, 0.30885471,
       0.30336047])

In [59]:
recommended_itemids = recommended_itemids[1:]
similarity_scores = similarity_scores[1:]

In [60]:
recommended_itemids

Index([147758, 119022, 331919, 303129, 358775, 10928, 43849, 179634, 396926,
       222126],
      dtype='int64', name='itemid')

In [61]:
recommendations = pd.DataFrame({
    "itemid": recommended_itemids,
    "similarity": similarity_scores
})

recommendations

,itemid,similarity
0,147758,0.527107
1,119022,0.380326
2,331919,0.368194
3,303129,0.356436
4,358775,0.356298
5,10928,0.353955
6,43849,0.330208
7,179634,0.323810
8,396926,0.308855
9,222126,0.303360


In [62]:
df["event"].value_counts()

event
view           2664312
addtocart        69332
transaction      22457
Name: count, dtype: int64

In [63]:
event_weights = {
    "view": 1,
    "addtocart": 3,
    "transaction": 5
}

In [64]:
df["interaction_score"] = df["event"].map(event_weights)

In [65]:
df[["visitorid", "itemid", "event", "interaction_score"]].head(10)

,visitorid,itemid,event,interaction_score
0,257597,355908,view,1
1,992329,248676,view,1
2,111016,318965,view,1
3,483717,253185,view,1
4,951259,367447,view,1
5,972639,22556,view,1
6,810725,443030,view,1
7,794181,439202,view,1
8,824915,428805,view,1
9,339335,82389,view,1


In [66]:
df.duplicated(subset=["visitorid", "itemid"]).sum()

np.int64(610922)

In [67]:
user_item = (
    df.groupby(["visitorid", "itemid"])["interaction_score"]
      .sum()
      .reset_index()
)

In [68]:
user_item.head()

,visitorid,itemid,interaction_score
0,0,67045,1
1,0,285930,1
2,0,357564,1
3,1,72028,1
4,2,216305,2


In [69]:
user_item.shape

(2145179, 3)

In [70]:
user_item["visitorid"].nunique(), user_item["itemid"].nunique()

(1407580, 235061)

In [71]:
user_ids = user_item["visitorid"].unique()

user_to_index = {user_id: i for i, user_id in enumerate(user_ids)}

In [72]:
user_item["user_index"] = user_item["visitorid"].map(user_to_index)

In [73]:
item_ids = user_item["itemid"].unique()

item_to_index = {item_id: i for i, item_id in enumerate(item_ids)}

In [74]:
user_ids = user_item["visitorid"].unique()

user_to_index = {user_id: i for i, user_id in enumerate(user_ids)}

user_item["user_index"] = user_item["visitorid"].map(user_to_index)

In [75]:
user_item.head()

,visitorid,itemid,interaction_score,user_index
0,0,67045,1,0
1,0,285930,1,0
2,0,357564,1,0
3,1,72028,1,1
4,2,216305,2,2


In [76]:
user_item["item_index"] = user_item["itemid"].map(item_to_index)

In [77]:
user_item.head()

,visitorid,itemid,interaction_score,user_index,item_index
0,0,67045,1,0,0
1,0,285930,1,0,1
2,0,357564,1,0,2
3,1,72028,1,1,3
4,2,216305,2,2,4


## Building Sparse Matrix

In [78]:
from scipy.sparse import csr_matrix

In [79]:
user_item_matrix = csr_matrix(
    (
        user_item["interaction_score"],
        (user_item["user_index"], user_item["item_index"])
    )
)

In [ ]:
user_item_matrix.shape ## (users,products)

(1407580, 235061)

## Non Zero Values

In [81]:
user_item_matrix.nnz

2145179

In [82]:
user_index = 0
user_row = user_item_matrix[user_index]

user_row.nnz

3

## This gives the item indexes of the products that user has interacted with.

In [83]:
user_row.indices

array([0, 1, 2], dtype=int32)

## score

In [84]:
user_row.data

array([1, 1, 1])

In [85]:
from sklearn.metrics.pairwise import cosine_similarity


In [86]:
target_user = 0

In [87]:
target_user_row = user_item_matrix[target_user]

## Compare User 0 with every user in the entire matrix.

In [88]:
user_similarity = cosine_similarity(
    target_user_row,
    user_item_matrix
)

In [90]:
user_similarity.shape


(1, 1407580)

In [91]:
similar_users = user_similarity[0].argsort()[::-1][:10]

similar_users

array([      0, 1369472, 1320671,  339176,  663929, 1264675, 1250913,
        780587, 1118084,  812012])

In [93]:
similar_users = similar_users[1:]

similar_users

array([1320671,  339176,  663929, 1264675, 1250913,  780587, 1118084,
        812012])

In [96]:
similar_user = similar_users[0]
similar_user

np.int64(1320671)

In [97]:
similar_user_row = user_item_matrix[similar_user]

In [101]:
similar_user = similar_users[0]

similar_user_row = user_item_matrix[similar_user]

similar_user_row.indices

array([1, 2], dtype=int32)

In [102]:
similar_user_row.data

array([1, 2])

In [105]:
index_to_item = {
    index: item_id
    for item_id, index in item_to_index.items()
}

similar_item_ids = [
    index_to_item[i]
    for i in similar_user_row.indices
]

similar_item_ids

[np.int64(285930), np.int64(357564)]

In [106]:
candidate_items = []

In [107]:
for user in similar_users:
    user_row = user_item_matrix[user]
    
    for item_index in user_row.indices:
        candidate_items.append(item_index)

In [108]:
len(candidate_items)

20

In [109]:
user_items = set(target_user_row.indices)

candidate_items = [
    item for item in candidate_items
    if item not in user_items
]

In [110]:
len(candidate_items)

6

In [111]:
user_items

{np.int32(0), np.int32(1), np.int32(2)}

In [112]:
from collections import Counter

item_counts = Counter(candidate_items)

In [113]:
item_counts

Counter({np.int32(1929): 2,
         np.int32(48473): 1,
         np.int32(139587): 1,
         np.int32(45162): 1,
         np.int32(68367): 1})

In [115]:
candidate_item_ids = [
    index_to_item[item_index]
    for item_index in item_counts.keys()
]
candidate_item_ids

[np.int64(133398),
 np.int64(48240),
 np.int64(420016),
 np.int64(451346),
 np.int64(287045)]

In [116]:
similar_user_scores = {
    user: user_similarity[0][user]
    for user in similar_users
}

similar_user_scores

{np.int64(1320671): np.float64(0.7745966692414834),
 np.int64(339176): np.float64(0.7745966692414834),
 np.int64(663929): np.float64(0.7071067811865477),
 np.int64(1264675): np.float64(0.6666666666666669),
 np.int64(1250913): np.float64(0.6666666666666669),
 np.int64(780587): np.float64(0.6123724356957945),
 np.int64(1118084): np.float64(0.5773502691896258),
 np.int64(812012): np.float64(0.5773502691896258)}

In [117]:
candidate_scores = {}
for user, similarity_score in similar_user_scores.items():
    user_row = user_item_matrix[user]

    for item_index in user_row.indices:
        if item_index not in user_items:
            candidate_scores[item_index] = (
                candidate_scores.get(item_index, 0) + similarity_score
            )
candidate_scores

{np.int32(1929): np.float64(1.3194792168823422),
 np.int32(48473): np.float64(0.6666666666666669),
 np.int32(139587): np.float64(0.6666666666666669),
 np.int32(45162): np.float64(0.6123724356957945),
 np.int32(68367): np.float64(0.6123724356957945)}

In [ ]:
ranked_candidates = sorted(
    candidate_scores.items(),
    key=lambda x: x[1],
    reverse=True
)

ranked_candidates

[(np.int32(1929), np.float64(1.3194792168823422)),
 (np.int32(48473), np.float64(0.6666666666666669)),
 (np.int32(139587), np.float64(0.6666666666666669)),
 (np.int32(45162), np.float64(0.6123724356957945)),
 (np.int32(68367), np.float64(0.6123724356957945))]